#!/bin/bash
# Artist Image Download Helper Script
# This script provides search URLs for finding representative images

echo "================================================================================"
echo "ARTIST IMAGE COLLECTION GUIDE"
echo "================================================================================"
echo ""
echo "For each artist below, click the search link to find representative work."
echo "Save images to: images/artists/[filename]"
echo ""
echo "Recommended image specs:"
echo "  - Format: JPG"
echo "  - Width: 800-1200px"
echo "  - Aspect ratio: 4:3 preferred"
echo "  - File size: <300KB"
echo ""
echo "================================================================================"
echo ""

# Array of artists: "Name|filename|search-query"
artists=(
    "Vera Molnár|vera-molnar.jpg|Vera+Molnar+computational+art"
    "Harold Cohen / AARON|harold-cohen-aaron.jpg|Harold+Cohen+AARON+artwork"
    "Trevor Paglen|trevor-paglen.jpg|Trevor+Paglen+artwork"
    "Sam Lavigne|sam-lavigne.jpg|Sam+Lavigne+art+project"
    "Tega Brain|tega-brain.jpg|Tega+Brain+artwork"
    "Zach Lieberman|zach-lieberman.jpg|Zach+Lieberman+creative+coding"
    "American Artist|american-artist.jpg|American+Artist+artwork"
    "teamLab|teamlab.jpg|teamLab+installation"
    "Eric Hu|eric-hu.jpg|Eric+Hu+typography+design"
    "Certain Measures|certain-measures.jpg|Certain+Measures+architecture"
    "JODI|jodi.jpg|JODI+net+art"
    "Casey Reas|casey-reas.jpg|Casey+Reas+processing+artwork"
    "Ian Cheng|ian-cheng.jpg|Ian+Cheng+artwork"
    "Holly Herndon & Mat Dryhurst|holly-herndon-mat-dryhurst.jpg|Holly+Herndon+Mat+Dryhurst"
    "Aranda\\Lasch|aranda-lasch.jpg|Aranda+Lasch+architecture"
    "Jenny Sabin Studio|jenny-sabin.jpg|Jenny+Sabin+architecture"
    "Neri Oxman|neri-oxman.jpg|Neri+Oxman+design"
    "Matter Design|matter-design.jpg|Matter+Design+architecture"
    "Nervous System|nervous-system.jpg|Nervous+System+jewelry+design"
    "Manfred Mohr|manfred-mohr.jpg|Manfred+Mohr+algorithmic+art"
    "John Maeda|john-maeda.jpg|John+Maeda+design"
    "Muriel Cooper|muriel-cooper.jpg|Muriel+Cooper+MIT+Media+Lab+design"
    "Golan Levin|golan-levin.jpg|Golan+Levin+interactive+art"
    "Lauren Lee McCarthy|lauren-lee-mccarthy.jpg|Lauren+Lee+McCarthy+artwork"
    "Hito Steyerl|hito-steyerl.jpg|Hito+Steyerl+video+art"
    "Pierre Huyghe|pierre-huyghe.jpg|Pierre+Huyghe+installation"
    "Cory Arcangel|cory-arcangel.jpg|Cory+Arcangel+artwork"
    "Cao Fei|cao-fei.jpg|Cao+Fei+artwork"
    "Lu Yang|lu-yang.jpg|Lu+Yang+artwork"
    "Rachel Rossin|rachel-rossin.jpg|Rachel+Rossin+VR+art"
    "Ryoji Ikeda|ryoji-ikeda.jpg|Ryoji+Ikeda+installation"
    "Ubermorgen|ubermorgen.jpg|Ubermorgen+net+art"
    "Rafaël Rozendaal|rafael-rozendaal.jpg|Rafael+Rozendaal+website+art"
    "Auriea Harvey|auriea-harvey.jpg|Auriea+Harvey+artwork"
    "Sougwen Chung|sougwen-chung.jpg|Sougwen+Chung+drawing+robot"
    "Refik Anadol|refik-anadol.jpg|Refik+Anadol+data+sculpture"
    "Mario Klingemann|mario-klingemann.jpg|Mario+Klingemann+AI+art"
    "Stephanie Dinkins|stephanie-dinkins.jpg|Stephanie+Dinkins+AI+artwork"
    "Anna Ridler|anna-ridler.jpg|Anna+Ridler+AI+art"
    "Rafael Lozano-Hemmer|rafael-lozano-hemmer.jpg|Rafael+Lozano-Hemmer+installation"
    "Random International|random-international.jpg|Random+International+Rain+Room"
    "Jennifer Steinkamp|jennifer-steinkamp.jpg|Jennifer+Steinkamp+projection"
    "Jim Campbell|jim-campbell.jpg|Jim+Campbell+LED+sculpture"
    "Maya Man|maya-man.jpg|Maya+Man+generative+art"
    "Surya Mattu|surya-mattu.jpg|Surya+Mattu+data+journalism"
    "Roopa Vasudevan|roopa-vasudevan.jpg|Roopa+Vasudevan+artwork"
    "Mimi Ọnụọha|mimi-onuoha.jpg|Mimi+Onuoha+data+art"
    "Morehshin Allahyari|morehshin-allahyari.jpg|Morehshin+Allahyari+3D+printing"
    "Ben Fry|ben-fry.jpg|Ben+Fry+data+visualization"
    "Richard The|richard-the.jpg|Richard+The+typography"
    "Laura Coombs|laura-coombs.jpg|Laura+Coombs+design"
    "Luna Maurer / Conditional Design|luna-maurer-conditional-design.jpg|Luna+Maurer+Conditional+Design"
    "Rune Madsen|rune-madsen.jpg|Rune+Madsen+computational+design"
    "Giorgia Lupi|giorgia-lupi.jpg|Giorgia+Lupi+data+humanization"
    "Jer Thorp|jer-thorp.jpg|Jer+Thorp+data+visualization"
    "Laurel Schwulst|laurel-schwulst.jpg|Laurel+Schwulst+web+design"
    "Metahaven|metahaven.jpg|Metahaven+design+studio"
    "David Reinfurt|david-reinfurt.jpg|David+Reinfurt+O-R-G+design"
    "Mindy Seu|mindy-seu.jpg|Mindy+Seu+Cyberfeminism+Index"
    "John Provencher|john-provencher.jpg|John+Provencher+design"
    "Bret Victor|bret-victor.jpg|Bret+Victor+interface+design"
    "Tristan Perich|tristan-perich.jpg|Tristan+Perich+sound+art+1-bit"
    "Mendi + Keith Obadike|mendi-keith-obadike.jpg|Mendi+Keith+Obadike+sound+art"
)

counter=1
for artist in "${artists[@]}"; do
    IFS='|' read -r name filename query <<< "$artist"

    echo "$counter. $name"
    echo "   Filename: images/artists/$filename"
    echo "   Search: https://duckduckgo.com/?q=$query&iax=images&ia=images"
    echo ""

    ((counter++))
done

echo "================================================================================"
echo "QUICK TIP: Use ImageMagick to batch resize after downloading:"
echo "  mogrify -resize '1200x900>' -quality 85 images/artists/*.jpg"
echo "================================================================================"
