// List of all images in /images/ directory with metadata
// Each entry has: src (path), title (optional), author (optional)
// Empty strings for title/author will not display attribution

const ALL_IMAGES = [
    // Happening images
    { src: 'images/happening/2025-09-16 16.22.10.jpg', title: '', author: '' },
    { src: 'images/happening/2025-09-18 11.10.47.jpg', title: '', author: '' },
    { src: 'images/happening/2025-09-18 11.11.39.jpg', title: '', author: 'Kyla Yeung' },
    { src: 'images/happening/2025-09-22 12.43.21.jpg', title: '', author: 'Leo Knudson' },
    // Student images
    { src: 'images/students/2025-09-25 11.38.30.jpg', title: '', author: '' },
    { src: 'images/students/2025-09-25 11.38.45.jpg', title: '', author: '' },
    { src: 'images/students/2025-09-25 11.40.12.jpg', title: '', author: '' },
    { src: 'images/students/2025-09-25 11.40.47.jpg', title: '', author: '' },
    { src: 'images/students/2025-09-25 11.41.51.jpg', title: '', author: 'Haohan Wen' },
    { src: 'images/students/2025-09-25 11.42.10.jpg', title: '', author: '' },
    { src: 'images/students/2025-09-25 17.53.56.jpg', title: '', author: 'Haohan Wen' },
    { src: 'images/students/2025-11-13 18.05.51.jpg', title: '', author: '' },
    { src: 'images/students/DSC06342.jpg', title: '', author: '' },
    // Happening images (DSC series)
    { src: 'images/happening/DSC06343.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06351.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06354.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06360.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06361.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06364.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06367.jpg', title: '', author: '' },
    // Student images (DSC series)
    { src: 'images/students/DSC06370.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06371.jpg', title: '', author: '' },
    { src: 'images/students/DSC06373.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06377.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06380.jpg', title: '', author: '' },
    { src: 'images/students/DSC06386.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06387.jpg', title: '', author: '' },
    { src: 'images/students/DSC06388.jpg', title: '', author: '' },
    { src: 'images/students/DSC06390.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06394.jpg', title: '', author: '' },
    { src: 'images/students/DSC06395.jpg', title: '', author: '' },
    { src: 'images/students/DSC06396.jpg', title: '', author: '' },
    { src: 'images/students/DSC06397.jpg', title: '', author: '' },
    { src: 'images/students/DSC06398.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06399.jpg', title: '', author: '' },
    { src: 'images/students/DSC06400.jpg', title: '', author: '' },
    { src: 'images/students/DSC06401.jpg', title: '', author: '' },
    { src: 'images/happening/DSC06403.jpg', title: '', author: '' },
    { src: 'images/students/DSC06404.jpg', title: '', author: '' },
    { src: 'images/students/DSC06405.jpg', title: '', author: '' },
    // Student images (ctc series)
    { src: 'images/students/ctc_01.jpg', title: '', author: '' },
    // Faculty images
    { src: 'images/faculty/ctc_04.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_05.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_07.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_08.jpg', title: '', author: '' },
    { src: 'images/students/ctc_09.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_10.jpg', title: '', author: '' },
    { src: 'images/students/ctc_12.jpg', title: '', author: '' },
    { src: 'images/students/ctc_15.jpg', title: '', author: '' },
    { src: 'images/students/ctc_17.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_20.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_23.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_24.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_25.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_26.jpg', title: '', author: '' },
    { src: 'images/students/ctc_27.jpg', title: '', author: '' },
    { src: 'images/students/ctc_28.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_32.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_33.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_34.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_35.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_36.jpg', title: '', author: '' },
    { src: 'images/students/ctc_37.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_39.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_40.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_41.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_43.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_44.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_45.jpg', title: '', author: '' },
    { src: 'images/students/ctc_46.jpg', title: '', author: '' },
    { src: 'images/students/ctc_47.jpg', title: '', author: '' },
    { src: 'images/students/ctc_48.jpg', title: '', author: '' },
    { src: 'images/students/ctc_49.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_50.jpg', title: '', author: '' },
    { src: 'images/students/ctc_51.jpg', title: '', author: '' },
    { src: 'images/students/ctc_52.jpg', title: '', author: '' },
    { src: 'images/students/ctc_53.jpg', title: '', author: '' },
    { src: 'images/students/ctc_54.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_55.jpg', title: '', author: '' },
    { src: 'images/students/ctc_59.jpg', title: '', author: '' },
    { src: 'images/students/ctc_60.jpg', title: '', author: '' },
    { src: 'images/students/ctc_61.jpg', title: '', author: '' },
    { src: 'images/students/ctc_63.jpg', title: '', author: '' },
    { src: 'images/students/ctc_64.jpg', title: '', author: '' },
    { src: 'images/students/ctc_65.jpg', title: '', author: '' },
    { src: 'images/students/ctc_66.jpg', title: '', author: '' },
    { src: 'images/students/ctc_67.jpg', title: '', author: '' },
    { src: 'images/students/ctc_68.jpg', title: '', author: '' },
    { src: 'images/students/ctc_72.jpg', title: '', author: '' },
    { src: 'images/students/ctc_76.jpg', title: '', author: '' },
    { src: 'images/students/ctc_77.jpg', title: '', author: '' },
    { src: 'images/students/ctc_78.jpg', title: '', author: '' },
    { src: 'images/students/ctc_79.jpg', title: '', author: '' },
    { src: 'images/students/ctc_81.jpg', title: '', author: '' },
    { src: 'images/students/ctc_82.jpg', title: '', author: '' },
    { src: 'images/students/ctc_85.jpg', title: '', author: '' },
    { src: 'images/happening/ctc_86.jpg', title: '', author: '' },
    { src: 'images/students/ctc_87.jpg', title: '', author: '' },
    { src: 'images/faculty/ctc_89.jpg', title: '', author: '' },
    { src: 'images/students/ctc_90.jpg', title: '', author: '' },
    { src: 'images/students/ctc_91.jpg', title: '', author: '' },
    // New student images
    { src: 'images/students/1.1.png', title: '', author: '' },
    { src: 'images/students/Armature (with titles).png', title: '', author: '' },
    { src: 'images/students/Render Experimentation.png', title: '', author: '' },
    { src: 'images/students/Screenshot 2026-01-27 at 4.18.50 PM.png', title: '', author: '' },
    { src: 'images/students/Screenshot 2026-01-27 at 4.19.08 PM.png', title: '', author: '' },
    { src: 'images/students/Screenshot 2026-01-27 at 4.20.20 PM.png', title: '', author: '' },
    // Additional happening images
    { src: 'images/happening/2025-10-16 19.33.49.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 15.20.26.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 15.20.30.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 15.21.01.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 15.36.59.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.30.28.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.30.33.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.30.43.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.31.15.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.31.27.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.31.33.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.31.53.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.32.39.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.32.54.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.33.03.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.33.34.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.33.47.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.34.07.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-13 18.34.32.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-14 16.57.39.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-14 16.57.48.jpg', title: '', author: '' },
    { src: 'images/happening/2025-11-18 13.20.49.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.13.31.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.32.56.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.33.14.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.43.51.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.45.08.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 12.45.20.jpg', title: '', author: '' },
    { src: 'images/happening/2026-01-21 13.10.59.jpg', title: '', author: '' }
];

// Export for use in slideshow.js
if (typeof window !== 'undefined') {
    window.ALL_IMAGES = ALL_IMAGES;
}
